import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {handleApi,resetApiState} from '../src/api.js';import {priceFixture} from './fixtures/market.js';
const req=p=>new Request('http://test.local'+p);
test('missing key and invalid ticker produce explicit failures',async()=>{resetApiState();assert.equal((await handleApi(req('/api/prices?symbol=AVGO'))).status,503);assert.equal((await handleApi(req('/api/prices?symbol=INVALID'),{ALPHAVANTAGE_API_KEY:'test'},{directoryFetcher:async()=>{throw Error('offline');}})).status,400);});
test('API is read-only and status does not return secrets',async()=>{const env={ALPHAVANTAGE_API_KEY:'TEST_PRIVATE_KEY'};const status=await handleApi(req('/api/status'),env);assert.ok(!(await status.text()).includes(env.ALPHAVANTAGE_API_KEY));assert.equal((await handleApi(new Request('http://x/api/status',{method:'POST'}),env)).status,405);});
test('identical concurrent requests coalesce; cached requests avoid new provider calls',async()=>{resetApiState();let calls=0;const env={ALPHAVANTAGE_API_KEY:'TEST_PRIVATE_KEY'};const context={fetcher:async url=>{calls++;assert.equal(url.hostname,'www.alphavantage.co');return new Response(JSON.stringify(priceFixture()));}};const [a,b]=await Promise.all([handleApi(req('/api/prices?symbol=AVGO'),env,context),handleApi(req('/api/prices?symbol=AVGO'),env,context)]);assert.equal(a.status,200);assert.equal(b.status,200);assert.equal(calls,1);const r=await handleApi(req('/api/prices?symbol=AVGO'),env,context);const text=await r.text();assert.equal(calls,1);assert.ok(!text.includes('TEST_PRIVATE_KEY'));assert.equal(JSON.parse(text).cacheHit,true);assert.equal(r.headers.get('Cache-Control'),'private, no-store');});
test('network errors never expose URLs or credentials',async()=>{resetApiState();const r=await handleApi(req('/api/prices?symbol=AVGO'),{ALPHAVANTAGE_API_KEY:'TEST_PRIVATE_KEY'},{fetcher:async()=>{throw new Error('https://example?apikey=TEST_PRIVATE_KEY')}});assert.equal(r.status,503);assert.ok(!(await r.text()).includes('TEST_PRIVATE_KEY'));});
test('built public assets have no server key references or synthetic generator',()=>{const js=fs.readFileSync('public/engine.js','utf8')+fs.readFileSync('public/app.js','utf8');assert.ok(!js.includes('ALPHAVANTAGE_API_KEY'));assert.ok(!js.includes('function rng('));assert.ok(!js.includes('makeStock('));});

test('edge-compatible transport rejects redirects without following credentials',async()=>{resetApiState();let calls=0;const r=await handleApi(req('/api/prices?symbol=AVGO'),{ALPHAVANTAGE_API_KEY:'TEST_PRIVATE_KEY'},{fetcher:async(url,options)=>{calls++;assert.equal(options.redirect,'manual');return new Response(null,{status:302,headers:{Location:'https://other.example/?apikey=TEST_PRIVATE_KEY'}});}});assert.equal(calls,1);assert.equal(r.status,502);const body=await r.text();assert.equal(JSON.parse(body).error.code,'UPSTREAM_REDIRECT');assert.ok(!body.includes('TEST_PRIVATE_KEY'));});
