import test from 'node:test';import assert from 'node:assert/strict';
import {capitalApi,resetCapitalState,normalizeCapital} from '../src/capital.js';
const env={CAPITAL_OWNER_EMAIL:'owner@example.test',CAPITAL_API_KEY:'TEST_KEY',CAPITAL_API_PASSWORD:'TEST_PASSWORD',CAPITAL_IDENTIFIER:'broker@example.test',CAPITAL_ACCOUNT_ID:'1234'};
const request=(method='GET',email=env.CAPITAL_OWNER_EMAIL)=>new Request('https://site.example/api/capital',{method,headers:email?{'oai-authenticated-user-email':email}:{}});
const account={accountId:'1234',accountName:'Test account',currency:'USD',balance:{balance:123,available:100,deposit:23,profitLoss:-2}};
function fixture(){const calls=[];const fetcher=async (url,options)=>{const path=new URL(url).pathname;calls.push([path,options.method]);assert.equal(options.redirect,'manual');if(path.endsWith('/session'))return Response.json({currentAccountId:'1234'},{headers:{CST:'TEST_CST','X-SECURITY-TOKEN':'TEST_TOKEN'}});if(path.endsWith('/accounts'))return Response.json({accounts:[account]});if(path.endsWith('/positions'))return Response.json({positions:[{position:{dealId:'TEST_DEAL',direction:'SELL',size:2,level:50,currency:'USD',upl:-4},market:{epic:'TEST',instrumentName:'Test instrument',bid:51,offer:52}}]});throw Error('Unexpected route');};return {calls,fetcher};}
test('Capital is owner-only, GET-only and does not contact broker for denied requests',async()=>{resetCapitalState();let calls=0;const capitalFetcher=()=>{calls++;throw Error('Must not run');};for(const method of ['POST','PUT','DELETE'])assert.equal((await capitalApi(request(method),env,{capitalFetcher})).status,405);for(const email of ['', 'other@example.test'])assert.equal((await capitalApi(request('GET',email),env,{capitalFetcher})).status,403);assert.equal(calls,0);});
test('live reads coalesce, preserve short CFD positions, cache privately and omit secrets',async()=>{resetCapitalState();const f=fixture(),context={capitalFetcher:f.fetcher};const [a,b]=await Promise.all([capitalApi(request(),env,context),capitalApi(request(),env,context)]);assert.equal(a.status,200);const data=await a.json();assert.equal(data.positions[0].direction,'SELL');assert.equal(data.positions[0].profitLoss,-4);assert.equal(data.positions[0].stop,null);assert.equal(data.account.profitLoss,-2);assert.equal(f.calls.length,3);await capitalApi(request(),env,context);assert.equal(f.calls.length,3);assert.equal(a.headers.get('Cache-Control'),'private, no-store');for(const value of [env.CAPITAL_API_KEY,env.CAPITAL_API_PASSWORD,env.CAPITAL_IDENTIFIER,'TEST_CST','TEST_TOKEN'])assert.ok(!JSON.stringify(data).includes(value));assert.deepEqual(f.calls.map(c=>c[1]),['POST','GET','GET']);assert.equal(b.status,200);});
test('wrong account fails closed without switching or reading positions',async()=>{resetCapitalState();const calls=[];const r=await capitalApi(request(),env,{capitalFetcher:async(url,options)=>{calls.push(options.method);return Response.json({currentAccountId:'OTHER'},{headers:{CST:'c','X-SECURITY-TOKEN':'t'}});}});assert.equal(r.status,409);assert.equal((await r.json()).error.code,'ACCOUNT_MISMATCH');assert.deepEqual(calls,['POST']);});
test('failed authentication is sanitized and backed off; missing data is not zero',async()=>{resetCapitalState();let calls=0;const capitalFetcher=async()=>{calls++;return Response.json({secret:env.CAPITAL_API_PASSWORD},{status:401});};const r=await capitalApi(request(),env,{capitalFetcher});assert.equal(r.status,401);assert.ok(!(await r.text()).includes(env.CAPITAL_API_PASSWORD));assert.equal((await capitalApi(request(),env,{capitalFetcher})).status,429);assert.equal(calls,1);assert.equal(normalizeCapital({...account,balance:{}},[]).account.balance,null);});
test('redirects are rejected and no token is forwarded to another host',async()=>{resetCapitalState();let calls=0;const r=await capitalApi(request(),env,{capitalFetcher:async()=>{calls++;return new Response(null,{status:302,headers:{Location:'https://other.example'}});}});assert.equal(r.status,502);assert.equal(calls,1);});
