const assert=require('node:assert/strict');const {chromium}=require('playwright');
(async()=>{const {createServer}=await import('../server.js');const {localDatabase}=await import('../src/local-db.js');const {normalizePrices,normalizeRevenue,normalizeEstimates}=await import('../src/provider.js');const {priceFixture,revenueFixture,estimatesFixture}=await import('./fixtures/market.js');const DB=localDatabase(':memory:');const server=createServer({DB});await new Promise(r=>server.listen(3070,'127.0.0.1',r));let browser;try{browser=await chromium.launch({executablePath:process.env.SWING_CHROMIUM_PATH||'/tmp/swing-browser/chromium',args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu','--no-zygote','--single-process','--disable-crashpad-for-testing']});const page=await browser.newPage({viewport:{width:1512,height:1000}});let priceRequests=0;const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.clock.setFixedTime(new Date('2026-09-21T00:00:00Z'));await page.route('**/api/**',async route=>{const u=new URL(route.request().url());if(u.pathname==='/api/prices')priceRequests++;let body;if(u.pathname==='/api/status')body={configured:true};else if(['/api/prices','/api/revenue','/api/estimates'].includes(u.pathname))body={source:'TEST FIXTURE',fetchedAt:'2026-09-21T00:00:00Z',value:u.pathname==='/api/prices'?normalizePrices(priceFixture()):u.pathname==='/api/revenue'?normalizeRevenue(revenueFixture()):normalizeEstimates(estimatesFixture())};else if(u.pathname==='/api/calendar')body={source:'TEST FIXTURE',fetchedAt:'2026-09-21T00:00:00Z',stale:false,value:[{ticker:'AVGO',date:'2026-12-10',estimate:2,currency:'USD'}]};else return route.continue();return route.fulfill({contentType:'application/json',body:JSON.stringify(body)});});await page.goto('http://127.0.0.1:3070');await page.waitForFunction(()=>!document.querySelector('#refresh-data').disabled);
assert.ok((await page.locator('#api-budget').innerText()).includes('0 / 70'));
assert.ok((await page.locator('#health-body').innerText()).includes('Not requested'));
const firstCycle=priceRequests;await page.clock.runFor(61000);await page.waitForFunction(()=>!document.querySelector('#refresh-data').disabled);assert.ok(priceRequests>=firstCycle+24);
await page.uncheck('#auto-refresh');const pausedCount=priceRequests;await page.clock.runFor(61000);assert.equal(priceRequests,pausedCount);
for(const [name,value] of Object.entries({entry:'100',stop:'90',target:'120',qty:'10',cost:'5',notes:'Browser verified plan'}))await page.locator(`#plan-form [name="${name}"]`).fill(value);await page.locator('#plan-form button[type="submit"]').click();await page.waitForFunction(()=>document.querySelector('#plan-status').textContent.includes('Plan saved'));await page.reload();await page.waitForFunction(()=>document.querySelector('#plan-list').textContent.includes('Browser verified plan'));assert.equal(await page.locator('#plan-list details').count(),1);
await page.locator('#plan-list summary').click();await page.locator('[data-plan-chart]').click();assert.ok((await page.locator('#plan-list').innerText()).includes('No original chart saved'));await page.click('#calendar-load');await page.waitForFunction(()=>document.querySelector('#calendar-results').textContent.includes('2026-12-10'));assert.ok((await page.locator('#calendar-results').innerText()).includes('Not supplied'));
await page.selectOption('#alert-form [name="type"]','stale');await page.click('#alert-form button[type="submit"]');await page.waitForFunction(()=>document.querySelector('#alert-events').textContent.includes('missing')||document.querySelector('#alert-events').textContent.includes('stale'));assert.equal(await page.locator('#alert-rules [data-alert-delete]').count(),1);
for(const [name,value] of Object.entries({entryDate:'2026-09-01',entry:'100',qty:'10',cost:'5',notes:'Verified journal'}))await page.locator(`#journal-form [name="${name}"]`).fill(value);await page.click('#journal-form button[type="submit"]');await page.waitForFunction(()=>document.querySelector('#journal-list').textContent.includes('Verified journal'));await page.click('#journal-list summary');await page.locator('[data-close-trade] [name="exit"]').fill('110');await page.locator('[data-close-trade] [name="exitDate"]').fill('2026-09-20');await page.click('[data-close-trade] button[type="submit"]');await page.waitForFunction(()=>document.querySelector('#journal-list').textContent.includes('Net P&L $95.00'));
await page.setInputFiles('#import-file',{name:'positions.csv',mimeType:'text/csv',buffer:Buffer.from('symbol,quantity,average_cost\nAVGO,2,100')});await page.waitForSelector('[data-map="avg"]');await page.click('#import-preview');await page.waitForFunction(()=>!document.querySelector('#import-confirm').disabled);assert.equal((await(await page.request.get('http://127.0.0.1:3070/api/records?kind=holdings')).json()).records.length,0);await page.click('#import-confirm');await page.waitForFunction(()=>document.querySelector('#holdings-body').textContent.includes('2 주'));
await page.selectOption('#import-mode','transactions');await page.setInputFiles('#import-file',{name:'trades.csv',mimeType:'text/csv',buffer:Buffer.from('id,symbol,side,quantity,price,date\nbroker-1,AVGO,buy,3,200,2026-09-02')});await page.waitForSelector('[data-map="id"]');await page.click('#import-preview');await page.waitForFunction(()=>!document.querySelector('#import-confirm').disabled);await page.click('#import-confirm');await page.waitForFunction(()=>document.querySelector('#holdings-body').textContent.includes('5 주'));await page.click('#import-preview');await page.waitForFunction(()=>document.querySelector('#import-results').textContent.includes('1 duplicate'));await page.click('#import-confirm');await page.waitForFunction(()=>document.querySelector('#sync-status').textContent.includes('1 duplicates'));assert.ok((await page.locator('#holdings-body').innerText()).includes('5 주'));
const second=await chromium.launch({executablePath:process.env.SWING_CHROMIUM_PATH||'/tmp/swing-browser/chromium',args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu','--no-zygote','--single-process','--disable-crashpad-for-testing']});const other=await second.newPage();await other.goto('http://127.0.0.1:3070');await other.waitForFunction(()=>document.querySelector('#holdings-count').textContent==='1');assert.ok((await other.locator('#holdings-body').innerText()).includes('AVGO'));await second.close();
for(const width of [390,768]){await page.setViewportSize({width,height:1000});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);}
assert.deepEqual(errors,[]);console.log('PASS: priorities 4–8: plans, calendar, alerts, journal, preview/confirm imports, duplicate prevention, cross-context holdings, and mobile/tablet layout.');
}finally{await browser?.close();server.close();DB.close();}})().catch(e=>{console.error(e);process.exit(1)});
