import test from 'node:test';import assert from 'node:assert/strict';
import {shortTermOutlook,outlookView} from '../public/outlook.js';
import {analyzeStock} from '../public/engine.js';import {normalizePrices} from '../src/provider.js';import {setupPriceFixture} from './fixtures/pullback.js';
const now=Date.parse('2026-09-21T00:00:00Z');
function stock(type='ready'){return analyzeStock({...normalizePrices(setupPriceFixture(type)),ticker:'TEST',revenue:[]});}
test('qualified uptrend explains price/volume evidence and conditional failure levels',()=>{const s=stock(),o=shortTermOutlook(s,now);assert.equal(o.tone,'positive');assert.ok(o.up.some(t=>t.includes('거래량')));assert.ok(o.conditions.some(t=>t.includes('이탈')));assert.ok(outlookView(s,10,false,now).includes('10거래일'));});
test('one-day rebound and high composite score never override failing long-term trend',()=>{const s=stock();s.score=95;s.setup.trendPass=false;s.setup.status='risk';s.setup.trend.find(t=>t.id==='above200').pass=false;s.setup.trend.find(t=>t.id==='slope50').pass=false;s.setup.trend.find(t=>t.id==='slope50').value=-7.52;const o=shortTermOutlook(s,now);assert.equal(o.tone,'negative');assert.ok(o.summary.includes('반등'));assert.ok(o.down.some(t=>t.includes('-7.52%')));assert.ok(o.up.some(t=>t.includes('전일 고가')));});
test('stale revenue does not label current price analysis old; stale price does',()=>{const s=stock();s.transportStale=true;s.priceTransportStale=false;s.revenueTransportStale=true;assert.equal(shortTermOutlook(s,now).old,false);assert.ok(shortTermOutlook(s,now).limits.includes('매출 자료'));s.priceTransportStale=true;assert.equal(shortTermOutlook(s,now).tone,'neutral');assert.equal(shortTermOutlook(s,now).old,true);});
test('unknown history and aged session do not issue current directional conclusions',()=>{const s=stock();assert.equal(shortTermOutlook(s,Date.parse('2026-10-02')).tone,'neutral');s.setup.status='unknown';assert.deepEqual(shortTermOutlook(s,now).up,[]);});
