import test from 'node:test';import assert from 'node:assert/strict';
import {normalizePrices,normalizeRevenue,normalizeEstimates,validateProviderResponse} from '../src/provider.js';
import {priceFixture,revenueFixture,estimatesFixture} from './fixtures/market.js';
test('normalizes dated real-provider-shaped OHLCV and revenue',()=>{const p=normalizePrices(priceFixture());assert.equal(p.asOf,'2026-09-18');assert.equal(p.bars.length,120);assert.ok(p.bars.every((b,i)=>!i||b.date>p.bars[i-1].date));const r=normalizeRevenue(revenueFixture());assert.equal(r.at(-1).value,8000);assert.equal(r.at(-1).currency,'USD');});
test('split history corrects pre-split prices and volumes without adjusting event day',()=>{const data=priceFixture(),dates=Object.keys(data['Time Series (Daily)']).sort();const date=dates.at(-2),prev=dates.at(-3),a=data['Time Series (Daily)'][date],b=data['Time Series (Daily)'][prev];a['8. split coefficient']='2';const result=normalizePrices(data);assert.equal(result.bars.at(-2).close,Number(a['4. close']));assert.equal(result.bars.at(-3).close,Number(b['4. close'])/2);assert.equal(result.bars.at(-3).volume,Number(b['6. volume'])*2);});
test('provider messages become sanitized actionable errors',()=>{assert.throws(()=>validateProviderResponse({Information:'API rate limit'}),e=>e.code==='RATE_LIMIT');assert.throws(()=>validateProviderResponse({'Error Message':'secret-url-apikey=xx'}),e=>!e.message.includes('apikey'));});
test('null revenue is not converted to zero or silently skipped',()=>{const data=revenueFixture();data.quarterlyReports[2].totalRevenue='None';assert.throws(()=>normalizeRevenue(data),e=>e.code==='INCOMPLETE_REVENUE');});
test('analyst estimates are separate records, not a manufactured guidance revision series',()=>{const data=normalizeEstimates(estimatesFixture());assert.equal(data.length,2);assert.equal(data[0].revenueAverage,2e10);assert.equal(data[0].epsHistory[0].value,null);assert.equal(data[0].epsHistory.at(-1).value,3.1);});

test('higher API call volume notice is throttling, not invalid credentials',()=>{assert.throws(()=>validateProviderResponse({Information:'Thank you for using Alpha Vantage! Please contact premium@alphavantage.co if you are targeting a higher API call volume.'}),e=>e.code==='RATE_LIMIT'&&e.status===429);});
