const assert=require('node:assert/strict');const {chromium}=require('playwright');
(async()=>{const {createServer}=await import('../server.js'),{localDatabase}=await import('../src/local-db.js'),{fixture}=await import('./fixtures/snowflake.js');const DB=localDatabase(':memory:');const {universe}=await import('../public/engine.js');const now=Date.now();
for(const [i,s] of universe.entries()){const sources=fixture().sources;sources.OVERVIEW.value={...sources.OVERVIEW.value,Symbol:s.ticker,Name:s.name,Industry:i%2?'Semiconductors':'Software',Description:'TEST FIXTURE cloud data centres',Currency:'USD',MarketCapitalization:1000000000*(i+1)};if(i%2)sources.OVERVIEW.value.PERatio=50;if(i===0)delete sources.OVERVIEW.value.PERatio;for(const [kind,packet] of Object.entries(sources))await DB.prepare('INSERT INTO market_cache (key,ticker,kind,payload,expires,succeeded_at,attempted_at) VALUES (?,?,?,?,?,?,?)').bind(kind+':'+s.ticker,s.ticker,kind,JSON.stringify({value:packet.value,fetchedAt:new Date(now).toISOString(),source:'TEST FIXTURE'}),now+86400000,new Date(now).toISOString(),new Date(now).toISOString()).run();}
const server=createServer({DB});await new Promise(r=>server.listen(3080,'127.0.0.1',r));let browser;try{browser=await chromium.launch({executablePath:'/tmp/swing-browser/chromium',args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu','--no-zygote','--single-process','--disable-crashpad-for-testing']});const page=await browser.newPage({viewport:{width:1512,height:1100}});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('http://127.0.0.1:3080/#snowflake');await page.waitForFunction(()=>document.querySelectorAll('[data-snow-detail]').length===24);await page.waitForFunction(()=>!document.querySelector('#snow-refresh').disabled);
await page.fill('#snow-query','NVDA');assert.equal(await page.locator('[data-snow-detail]').count(),1);await page.locator('[data-snow-range="Value"]').fill('1');assert.equal(await page.locator('[data-snow-detail]').count(),0);await page.click('#snow-reset');await page.selectOption('#snow-industry','Semiconductors');assert.equal(await page.locator('[data-snow-detail]').count(),12);await page.click('#snow-reset');await page.selectOption('#snow-sort','marketCap');assert.equal(await page.locator('[data-snow-detail]').first().getAttribute('data-snow-detail'),universe.at(-1).ticker);
await page.locator('[data-axis="0"]').focus();await page.keyboard.press('ArrowUp');assert.equal(await page.locator('[data-snow-range="Value"]').inputValue(),'1');assert.equal(await page.locator('[data-snow-detail]').count(),23);
await page.click('#snow-reset');const handle=page.locator('[data-axis="1"]'),box=await handle.boundingBox(),svg=await page.locator('#snow-filter-chart svg').boundingBox();await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(svg.x+svg.width*.766,svg.y+svg.height*.413,{steps:5});await page.mouse.up();assert.equal(await page.locator('[data-snow-range="Future"]').inputValue(),'5');
await page.click('#snow-reset');await page.locator('[data-snow-preset]').first().click();assert.equal(await page.locator('[data-snow-range="Health"]').inputValue(),'3');await page.locator('[data-snow-detail="AVGO"]').click();assert.equal(await page.locator('#snow-detail').isVisible(),true);assert.ok((await page.locator('#snow-detail-content').innerText()).includes('Positive P/E below 25'));await page.click('#snow-detail-close');
await page.locator('#snowflake').scrollIntoViewIfNeeded();await page.evaluate(()=>document.querySelector('#snowflake').scrollIntoView({behavior:'instant',block:'start'}));await page.screenshot({path:'artifacts/snowflake-desktop.png',fullPage:false});for(const width of [390,768]){await page.setViewportSize({width,height:1000});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);}await page.setViewportSize({width:390,height:1000});await page.evaluate(()=>document.querySelector('#snowflake').scrollIntoView({behavior:'instant',block:'start'}));await page.screenshot({path:'artifacts/snowflake-mobile.png',fullPage:false});assert.deepEqual(errors,[]);console.log('PASS: snowflake search, missing-data filters, industry, sort, keyboard, pointer drag, presets, evidence modal, mobile/tablet overflow. TEST FIXTURE data only.');
}finally{await browser?.close();server.close();DB.close();}})().catch(e=>{console.error(e);process.exit(1)});
