import {applyTransactions} from '../public/import-model.js';import {validateHoldings} from '../public/engine.js';
const json=(d,status=200)=>new Response(JSON.stringify(d),{status,headers:{'Content-Type':'application/json','Cache-Control':'private, no-store'}});
export async function holdingsImport(request,env,context={}){
 const user=context.localUserId||request.headers.get('oai-authenticated-user-id'),url=new URL(request.url);if(!user)return json({error:{message:'Sign in to import holdings.'}},401);if(!env.DB)return json({error:{message:'Private storage unavailable.'}},503);if(request.method!=='POST')return json({error:{message:'Use POST.'}},405);if(request.headers.get('origin')!==url.origin)return json({error:{message:'Same-origin requests required.'}},403);if(!(request.headers.get('content-type')||'').startsWith('application/json'))return json({error:{message:'JSON required.'}},415);
 try{const raw=await request.text();if(raw.length>80000)return json({error:{message:'Import is too large.'}},413);const body=JSON.parse(raw);if(!body||!['positions','transactions'].includes(body.mode)||!Number.isInteger(body.revision)||body.revision<0)throw Error('Invalid import request.');const existing=await env.DB.prepare("SELECT revision,payload FROM user_records WHERE user_id=? AND kind='holdings' AND id='portfolio'").bind(user).first();const revision=existing?.revision||0,positions=existing?JSON.parse(existing.payload).positions:[];
 if(revision!==body.revision)return json({error:{message:'Holdings changed on another device. Reload and preview again.'}},409);
 let result;if(body.mode==='positions'){if(!validateHoldings(body.rows))throw Error('Invalid positions.');result={positions:body.rows,added:[],skipped:0};}else{const previous=(await env.DB.prepare("SELECT payload FROM user_records WHERE user_id=? AND kind='transactions'").bind(user).all()).results;result=applyTransactions(positions,body.rows,previous.map(r=>JSON.parse(r.payload)));}
 if(url.pathname==='/api/import-preview')return json({...result,revision,mode:body.mode});
 const same=JSON.stringify([...positions].sort((a,b)=>a.ticker.localeCompare(b.ticker)))===JSON.stringify([...result.positions].sort((a,b)=>a.ticker.localeCompare(b.ticker)));if(same&&!result.added.length)return json({saved:true,revision,positions,skipped:result.skipped,added:0});
 const token=crypto.randomUUID(),payload=JSON.stringify({positions:result.positions,importToken:token}),now=new Date().toISOString();
 const update=revision===0?env.DB.prepare("INSERT INTO user_records (user_id,kind,id,revision,payload,updated_at) VALUES (?,'holdings','portfolio',1,?,?) ON CONFLICT(user_id,kind,id) DO NOTHING").bind(user,payload,now):env.DB.prepare("UPDATE user_records SET payload=?,revision=revision+1,updated_at=? WHERE user_id=? AND kind='holdings' AND id='portfolio' AND revision=?").bind(payload,now,user,revision);
 const statements=[update,...result.added.map(row=>env.DB.prepare("INSERT INTO user_records (user_id,kind,id,revision,payload,updated_at) SELECT ?,'transactions',?,1,?,? FROM user_records WHERE user_id=? AND kind='holdings' AND id='portfolio' AND revision=? AND json_extract(payload,'$.importToken')=?").bind(user,row.id,JSON.stringify(row),now,user,revision+1,token))];const applied=await env.DB.batch(statements);if(!(applied[0].meta?.changes??applied[0].changes))return json({error:{message:'Holdings changed. Reload and preview again.'}},409);return json({saved:true,revision:revision+1,positions:result.positions,skipped:result.skipped,added:result.added.length});
 }catch(e){const validation=e instanceof SyntaxError||/Invalid|Import|existing transaction|Sell exceeds|Resulting/.test(e.message);return json({error:{message:validation?e.message:'Import could not be saved. No partial import was committed.'}},validation?400:503);}
}
